version: '3.8'

services:
  db:
    image: mysql:8.0  # Use MySQL version 8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Root password for MySQL
      MYSQL_DATABASE: job_board          # Database to create
      MYSQL_USER: user                   # Username
      MYSQL_PASSWORD: userpassword       # Password for user
    ports:
      - "3306:3306"                      # Map MySQL port
    volumes:
      - db_data:/var/lib/mysql           # Store data persistently

  phpmyadmin:
    image: phpmyadmin/phpmyadmin         # Use phpMyAdmin image
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"                        # Expose phpMyAdmin on localhost:8080
    environment:
      PMA_HOST: db                       # Link to the database service
      PMA_USER: user                     # MySQL username
      PMA_PASSWORD: userpassword         # MySQL password
    depends_on:
      - db                               # Ensure MySQL starts first

volumes:
  db_data:
